### ISSUE TITLE
问题好多啊，发愁

### ISSUE THREAD

**Issue by thefristloser** [imalexyang/ExamStack#3]
上传附件不支持firefox，需要改好几个文件。
培训删除按钮不能用，没有修改功能
试题模板某些字段意义不明
某些业务逻辑混乱搞不清等等。，我感觉前途渺茫啊。

**Comment by imalexyang** [comment]
既是问题，也是进步和完善的动力，你可以在此基础上，更进一步，完善这个项目。

**Comment by thefristloser** [comment]
嗯。 没有设计文档/ku。 您还在维护这个项目嘛。

**Comment by imalexyang** [comment]
如果有人提出有bug会改一下，增加功能或者完善文档这个事情，近期没计划。
